#pragma once
#include <core.math/integration/implementation/singlestep/ExplicitEuler.h>
#include <core.math/integration/implementation/singlestep/ExplicitEuler.implementation.template.h>
#include <core.math/integration/implementation/singlestep/ImplicitEuler.h>
#include <core.math/integration/implementation/singlestep/ImplicitEuler.implementation.template.h>
#include <core.math/integration/implementation/singlestep/RungeKutta2.h>
#include <core.math/integration/implementation/singlestep/RungeKutta2.implementation.template.h>
#include <core.math/integration/implementation/singlestep/RungeKutta4.h>
#include <core.math/integration/implementation/singlestep/RungeKutta4.implementation.template.h>
//#include <core.math/integration/implementation/singlestep/RungeKuttaFehlberg45.h>
//#include <core.math/integration/implementation/singlestep/RungeKuttaFehlberg.implementation.template.h>
